/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CalendarEvent } from "./CalendarEvent";
import { CalendarEventCountArgs } from "./CalendarEventCountArgs";
import { CalendarEventFindManyArgs } from "./CalendarEventFindManyArgs";
import { CalendarEventFindUniqueArgs } from "./CalendarEventFindUniqueArgs";
import { CreateCalendarEventArgs } from "./CreateCalendarEventArgs";
import { UpdateCalendarEventArgs } from "./UpdateCalendarEventArgs";
import { DeleteCalendarEventArgs } from "./DeleteCalendarEventArgs";
import { Car } from "../../car/base/Car";
import { Student } from "../../student/base/Student";
import { Teacher } from "../../teacher/base/Teacher";
import { CalendarEventService } from "../calendarEvent.service";
@graphql.Resolver(() => CalendarEvent)
export class CalendarEventResolverBase {
  constructor(protected readonly service: CalendarEventService) {}

  async _calendarEventsMeta(
    @graphql.Args() args: CalendarEventCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CalendarEvent])
  async calendarEvents(
    @graphql.Args() args: CalendarEventFindManyArgs
  ): Promise<CalendarEvent[]> {
    return this.service.calendarEvents(args);
  }

  @graphql.Query(() => CalendarEvent, { nullable: true })
  async calendarEvent(
    @graphql.Args() args: CalendarEventFindUniqueArgs
  ): Promise<CalendarEvent | null> {
    const result = await this.service.calendarEvent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CalendarEvent)
  async createCalendarEvent(
    @graphql.Args() args: CreateCalendarEventArgs
  ): Promise<CalendarEvent> {
    return await this.service.createCalendarEvent({
      ...args,
      data: {
        ...args.data,

        car: args.data.car
          ? {
              connect: args.data.car,
            }
          : undefined,

        student: args.data.student
          ? {
              connect: args.data.student,
            }
          : undefined,

        teacher: args.data.teacher
          ? {
              connect: args.data.teacher,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CalendarEvent)
  async updateCalendarEvent(
    @graphql.Args() args: UpdateCalendarEventArgs
  ): Promise<CalendarEvent | null> {
    try {
      return await this.service.updateCalendarEvent({
        ...args,
        data: {
          ...args.data,

          car: args.data.car
            ? {
                connect: args.data.car,
              }
            : undefined,

          student: args.data.student
            ? {
                connect: args.data.student,
              }
            : undefined,

          teacher: args.data.teacher
            ? {
                connect: args.data.teacher,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CalendarEvent)
  async deleteCalendarEvent(
    @graphql.Args() args: DeleteCalendarEventArgs
  ): Promise<CalendarEvent | null> {
    try {
      return await this.service.deleteCalendarEvent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Car, {
    nullable: true,
    name: "car",
  })
  async getCar(@graphql.Parent() parent: CalendarEvent): Promise<Car | null> {
    const result = await this.service.getCar(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Student, {
    nullable: true,
    name: "student",
  })
  async getStudent(
    @graphql.Parent() parent: CalendarEvent
  ): Promise<Student | null> {
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Teacher, {
    nullable: true,
    name: "teacher",
  })
  async getTeacher(
    @graphql.Parent() parent: CalendarEvent
  ): Promise<Teacher | null> {
    const result = await this.service.getTeacher(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
